language: csharp
sudo: false

dotnet: 2.1.4 # SDK version; includes runtime version 2.0.5. Need 2.0+ for netcoreapp2.0 tests.

mono: 5.10.0 # Need 5.2+ for the included MSBuild.

matrix:
  include:
    - os: osx
      install:
        - curl https://download.microsoft.com/download/A/7/E/A7EF2AFF-F77B-4F77-A21B-0F7BD09A4065/dotnet-osx-x64.1.1.6.pkg -O
        - sudo installer -pkg dotnet-osx-x64.1.1.6.pkg -target /

      osx_image: xcode9.1

script:
  - ls -la
  - msbuild
  - mono packages/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe monogame.Testes/bin/Debug/monogame.Testes.dll
